### ISSUE TITLE
是否可以提供mysql表设计

### ISSUE THREAD

**Issue by wuhaih** [zhaoluting/front-end-designer#2]
有幸看到你开源恭喜了基于vue可视化布局设计方案，特别感兴趣，但是下载下来用户名和密码输入需要服务连接，表示不知道怎么弄，是否可以提供mysql表设计呢，只要能正常跑起来就可以

**Comment by zhaoluting** [comment]
SQL脚本已传 👉https://github.com/zhaoluting/front-end-designer/blob/master/front-end-designer_2018-07-21.sql
